old_gtk_background='#fdfdfb'
old_gtk_accent='#A6C796'
old_gtk_secondary_background='#fafaf9'
old_gtk_third_background='#fafaf9'
old_gtk_inactive_background='#25262A'
old_gtk_inactive_background='#1C1E1F'