# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#fbf1f2'
foreground='#8b8198'
cursor='#8b8198'

# Colors
color0='#fbf1f2'
color1='#D57E85'
color2='#A3B367'
color3='#DCB16C'
color4='#7297B9'
color5='#BB99B4'
color6='#69A9A7'
color7='#8b8198'
color8='#bfb9c6'
color9='#D57E85'
color10='#A3B367'
color11='#DCB16C'
color12='#7297B9'
color13='#BB99B4'
color14='#69A9A7'
color15='#585062'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
